### PR TITLE
Add Fig.1.

### PR DESCRIPTION
**Pull request by tmozgach**

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman Would you like to mention "precompiled binaty bottle" somwhere? I added in the Architecture section. Take a look. 
This is link of our diagram, you can edit that.
https://drive.google.com/file/d/1eiz7So5Th0zxjiemlSTqLXHBdjjajsuW/view?usp=sharing

**Comment by sjackman** [comment]
> Figure 1 reveals the overview of ORCA architecture. Building the ORCA container image is completely automated

I suggest…

An overview of the ORCA architecture is shown in Fig. 1.

**Comment by sjackman** [comment]
> Would you like to mention "precompiled binaty bottle" somwhere?

Yes, thanks! I suggest…

Linuxbrew can install software in the user's home directory on Linux, macOS, or Windows, using Windows Subsystem for Linux, does not require administrator privileges, and provides precompiled binaries for many packages. [@Jackman2016].

When we mention how long it takes to build the ORCA image, in that same section or sentence, it should say that it's fast because it uses these precompiled binary bottles. Building all of the packages from source would be very time consuming.

**Comment by tmozgach** [comment]
@sjackman  Revised! =)

**Comment by sjackman** [comment]
Thanks, Tanya. I made some more revisions to the architecture section too.

**Pull request merged**
