### PR TITLE
First draft

### PR DESCRIPTION
**Pull request by tmozgach**

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman could you please quickly skim the content and tell me which part (ideas) I should extend, add or get rid of it without paying attention on the grammar, style, reference, structures?

**Comment by sjackman** [comment]
Looks great, Tanya!

Please update the PR to modify the file named `orca.md` rather than creating a new file (`content.rmd`).

Use the citation format `[@Author_Year]`, for example `[@Gruning_2017]` for Bioconda.
Update the file `orca.bib` with the Bibtex entries for each citation. You can use the web site https://www.doi2bib.org to convert a DOI to Bib:
For example, to get the Bibtex entry for Bioconda, you can use this URL https://www.doi2bib.org/bib/10.1101%2F207092 or this command line:
```sh
curl -LH "Accept: text/bibliography; style=bibtex" "http://dx.doi.org/10.1101/207092"
```

You can run `make orca.html orca.pdf` to render the manuscript to HTML and PDF to check that the references are working.

The introduction should describe the problem and other current solutions to the problem, and only briefly introduce our solution to the problem with a few sentences. Most of the second paragraph of the introduction should be moved to the Architecture section. Please cite the Linuxbrew poster.

> including over 400 validated bioinformatics

Please include a link to the list of installed packages.

"Case study" should be "Case studies". Please cite the Hackseq 2016 paper.

Looking good! How's the singularity work going? It'd be great to provide a singularity image on quay.io for this paper.

**Comment by tmozgach** [comment]
@sjackman I updated orca.bib and orca.md. Could you check please?

**Comment by sjackman** [comment]
> In fact, bioinformatics workflows and pipelines require complex applications and libraries, which have their own software dependencies as well [@Hung2016].

Can you clarify what you mean here? Do you mean a particular bioinformatics analysis, bioinformatics software, or workflow/pipeline software, like Galaxy? How is the citation `@Hung2016` relevant? I've revised like so.

Installing a bioinformatics tool requires first installing its dependencies, which themselves have dependencies, and on, and on.

**Comment by sjackman** [comment]
Please put the documentation in the `docs` folder. Please add links in the `README.md` to the documentation.

**Comment by sjackman** [comment]
I've revised the paper. Can you please give it a read over?

**Pull request merged**
